<a href="https://colab.research.google.com/github/vaishnavighadge2103/vaishnavi/blob/main/task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

question 1

**What is NumPy:-**

NumPy (Numerical Python) is a Python library used for numerical and mathematical computations.
It provides a powerful N-dimensional array (ndarray) object.
NumPy is faster and more memory-efficient than Python lists.

**Why is NumPy Important:-**

Performs mathematical operations efficiently.
Supports multi-dimensional arrays and matrices.
Faster execution compared to Python lists.
Provides many built-in mathematical functions.
Used as the foundation for many Python libraries.

In [3]:
#installation of NumPY
pip install numpy

#how to import NumPY
import numpy as np;

**Role of NumPy**
**NumPy is widely used in:**

*Data Science* – Data analysis and manipulation.
*Machine Learning* – Preparing and processing datasets.
*Scientific Computing* – Mathematical and scientific calculations.
*Artificial Intelligence* (AI) – Numerical computations for AI models.
*Data Visualization* – Works with libraries like Matplotlib and Pandas.

Question 2


**Arrays in NumPy:-**

ndarray (N-dimensional array) is the main object in NumPy.
It stores elements of the same data type.
It is faster and more memory-efficient than Python lists.

In [1]:
import numpy as np

# 1. Create array using np.array()
arr1 = np.array([10, 20, 30, 40, 50])
print("np.array():", arr1)

# 2. Create array using np.zeros()
arr2 = np.zeros(5)
print("np.zeros():", arr2)

# 3. Create array using np.ones()
arr3 = np.ones(5)
print("np.ones():", arr3)

# 4. Create array using np.arange()
arr4 = np.arange(1, 11, 2)
print("np.arange():", arr4)

# 5. Create array using np.linspace()
arr5 = np.linspace(1, 10, 5)
print("np.linspace():", arr5)

# Array Indexing
print("\nFirst Element:", arr1[0])
print("Last Element:", arr1[-1])

# Array Slicing
print("Elements from index 1 to 3:", arr1[1:4])

np.array(): [10 20 30 40 50]
np.zeros(): [0. 0. 0. 0. 0.]
np.ones(): [1. 1. 1. 1. 1.]
np.arange(): [1 3 5 7 9]
np.linspace(): [ 1.    3.25  5.5   7.75 10.  ]

First Element: 10
Last Element: 50
Elements from index 1 to 3: [20 30 40]


In [4]:
#Question 3
import numpy as np

# Create Arrays
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print("Array 1:", arr1)
print("Array 2:", arr2)

# 1. Arithmetic Operations
print("\nAddition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

# 2. Broadcasting
print("\nBroadcasting (arr1 + 5):", arr1 + 5)
print("Broadcasting (arr1 * 2):", arr1 * 2)

# 3. Element-wise Functions
print("\nSquare Root:", np.sqrt(arr1))
print("Sine:", np.sin(arr2))
print("Exponential:", np.exp(arr2))

Array 1: [10 20 30 40]
Array 2: [1 2 3 4]

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]

Broadcasting (arr1 + 5): [15 25 35 45]
Broadcasting (arr1 * 2): [20 40 60 80]

Square Root: [3.16227766 4.47213595 5.47722558 6.32455532]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Exponential: [ 2.71828183  7.3890561  20.08553692 54.59815003]


In [5]:
#Question 4
import numpy as np

# Create a 2D Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Array:")
print(arr)

# 1. Shape and Dimensions
print("\nShape:", arr.shape)
print("Dimensions:", arr.ndim)

# 2. Reshape
reshaped = arr.reshape(3, 2)
print("\nReshaped Array (3x2):")
print(reshaped)

# 3. Flatten
flat = arr.flatten()
print("\nFlatten Array:")
print(flat)

# 4. Transpose
trans = arr.transpose()
print("\nTranspose:")
print(trans)

# 5. Concatenate
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("\nConcatenate:")
print(np.concatenate((a, b)))

# 6. Vertical Stack
print("\nVertical Stack:")
print(np.vstack((a, b)))

# 7. Horizontal Stack
print("\nHorizontal Stack:")
print(np.hstack((a, b)))

# 8. Split Array
c = np.array([10, 20, 30, 40, 50, 60])

print("\nSplit Array:")
print(np.split(c, 3))

Original Array:
[[1 2 3]
 [4 5 6]]

Shape: (2, 3)
Dimensions: 2

Reshaped Array (3x2):
[[1 2]
 [3 4]
 [5 6]]

Flatten Array:
[1 2 3 4 5 6]

Transpose:
[[1 4]
 [2 5]
 [3 6]]

Concatenate:
[1 2 3 4 5 6]

Vertical Stack:
[[1 2 3]
 [4 5 6]]

Horizontal Stack:
[1 2 3 4 5 6]

Split Array:
[array([10, 20]), array([30, 40]), array([50, 60])]


In [6]:
#Question 5
import numpy as np

# Create a 2D Array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("Original Array:")
print(arr)

# 1. Indexing
print("\nFirst Element:", arr[0, 0])
print("Last Element:", arr[2, 2])

# 2. Slicing
print("\nFirst Row:", arr[0])
print("Second Column:", arr[:, 1])
print("Sub Array:")
print(arr[0:2, 1:3])

# 3. Masking (Logical Indexing)
print("\nElements Greater Than 40:")
print(arr[arr > 40])

# 4. Fancy Indexing
a = np.array([10, 20, 30, 40, 50])

print("\nOriginal 1D Array:", a)
print("Fancy Indexing:", a[[0, 2, 4]])

Original Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

First Element: 10
Last Element: 90

First Row: [10 20 30]
Second Column: [20 50 80]
Sub Array:
[[20 30]
 [50 60]]

Elements Greater Than 40:
[50 60 70 80 90]

Original 1D Array: [10 20 30 40 50]
Fancy Indexing: [10 30 50]


In [7]:
#Question 6

import numpy as np

# Create Arrays
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Array A:", a)
print("Array B:", b)

# 1. Universal Functions (ufuncs)
print("\nAddition:", np.add(a, b))
print("Subtraction:", np.subtract(a, b))
print("Multiplication:", np.multiply(a, b))

# 2. Statistical Functions
arr = np.array([10, 20, 30, 40, 50])

print("\nMean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

# 3. Linear Algebra Functions
m1 = np.array([[1, 2],
               [3, 4]])

m2 = np.array([[5, 6],
               [7, 8]])

print("\nDot Product:")
print(np.dot(m1, m2))

print("\nMatrix Multiplication:")
print(np.matmul(m1, m2))

print("\nInverse Matrix:")
print(np.linalg.inv(m1))

print("\nEigen Values and Eigen Vectors:")
values, vectors = np.linalg.eig(m1)
print("Eigen Values:")
print(values)
print("Eigen Vectors:")
print(vectors)

Array A: [10 20 30]
Array B: [1 2 3]

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0
Minimum: 10
Maximum: 50

Dot Product:
[[19 22]
 [43 50]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Inverse Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]

Eigen Values and Eigen Vectors:
Eigen Values:
[-0.37228132  5.37228132]
Eigen Vectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [8]:
# Question 7

import numpy as np

# 1. Random numbers between 0 and 1
print("Random Numbers (rand):")
print(np.random.rand(5))

# 2. Random integers
print("\nRandom Integers (randint):")
print(np.random.randint(1, 100, 5))

# 3. Seed Random Number Generation
np.random.seed(10)

print("\nRandom Numbers After Seed:")
print(np.random.rand(5))

# 4. Random Sampling
arr = np.array([10, 20, 30, 40, 50])

print("\nRandom Sample:")
print(np.random.choice(arr, 3))

# 5. Shuffle
a = np.array([1, 2, 3, 4, 5])

np.random.shuffle(a)
print("\nShuffled Array:")
print(a)

# 6. Permutation
b = np.array([1, 2, 3, 4, 5])

print("\nPermutation:")
print(np.random.permutation(b))

Random Numbers (rand):
[0.48190088 0.59432886 0.23139658 0.93757077 0.57691677]

Random Integers (randint):
[27 58 35 35 44]

Random Numbers After Seed:
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]

Random Sample:
[10 20 30]

Shuffled Array:
[4 3 5 2 1]

Permutation:
[4 2 5 3 1]


Question 8



**What is Broadcasting:-**

Broadcasting is a feature in NumPy that allows arithmetic operations between arrays of different shapes.
NumPy automatically expands the smaller array to match the shape of the larger array without copying data.

**Rules of Broadcasting:-**

Compare array shapes from right to left.
Two dimensions are compatible if:
      They are equal,
           or
      One of them is 1.
If the dimensions are not compatible, NumPy raises a ValueError.

In [9]:
import numpy as np

# Example 1: Broadcasting with Scalar
arr = np.array([10, 20, 30, 40])

print("Original Array:", arr)
print("Array + 5:", arr + 5)

# Example 2: Broadcasting with 1D Arrays
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("\nArray A:", a)
print("Array B:", b)
print("A + B:", a + b)

# Example 3: Broadcasting with 2D Array
c = np.array([[1], [2], [3]])
d = np.array([10, 20, 30])

print("\n2D Array:")
print(c)

print("\n1D Array:")
print(d)

print("\nBroadcasting Result:")
print(c + d)

Original Array: [10 20 30 40]
Array + 5: [15 25 35 45]

Array A: [1 2 3]
Array B: [10 20 30]
A + B: [11 22 33]

2D Array:
[[1]
 [2]
 [3]]

1D Array:
[10 20 30]

Broadcasting Result:
[[11 21 31]
 [12 22 32]
 [13 23 33]]
